language: python
sudo: false
python:
  - "2.7"
  - "3.5"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # install python dependencies
  - conda install --yes -q python=$TRAVIS_PYTHON_VERSION
  - python scripts/install-deps.py

env:
  - MLCOMP_TESTING=1

script:
  - nosetests --with-coverage --cover-package=mlcomp .

after_success:
  - coveralls
